// <auto-generated />
using System;
using Fsel.Cms.PlanetDefender.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fsel.Cms.PlanetDefender.Infrastructure.Migrations
{
    [DbContext(typeof(CmsPlanetDefenderDbContext))]
    [Migration("20231018065533_Drop_QuestBankTable")]
    partial class Drop_QuestBankTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fsel.Cms.PlanetDefender.Domain.Entities.StudentGameInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("StudentGameInfos");
                });

            modelBuilder.Entity("Fsel.Cms.PlanetDefender.Domain.Entities.ZMatter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ZMatters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("187c1ce2-23ad-4acc-ba89-649a437c1099"),
                            Code = "WB001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "A sword without a costume? Oh no, look, there's a sharp wind around it!",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wind Blade",
                            Usage = "Push 1 meteor, reset meteor duration to maximum"
                        },
                        new
                        {
                            Id = new Guid("9faaead9-d4de-4aa8-8523-5432fa7f313f"),
                            Code = "SW001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "What's the use of a broken watch?",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Stop Watch",
                            Usage = "Freeze time within X seconds"
                        },
                        new
                        {
                            Id = new Guid("baecdd2b-39c3-41a5-8240-1a48e37b4f33"),
                            Code = "SH001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "This shield is so beautiful! Wish it was here forever",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Shield",
                            Usage = "Quantum shield, helps the spacecraft block 1 damage"
                        },
                        new
                        {
                            Id = new Guid("54c17216-a173-4ed6-a6e8-ff7062494705"),
                            Code = "SP001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "The rescue ship is here!",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Supply Kit",
                            Usage = "Use immediately restores 10% of maximum health (Full will restore shield)"
                        },
                        new
                        {
                            Id = new Guid("0cf0c6b3-1312-473d-bd2a-15dfa88d6052"),
                            Code = "PU001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "This power...It's strange",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Power Up",
                            Usage = "Restores 20% rage"
                        },
                        new
                        {
                            Id = new Guid("fdc945ba-248e-4db2-96cb-c7d55a7de8c8"),
                            Code = "MG001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "With the force of fate, these meteorites need a little help",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Magnetic",
                            Usage = "Creates a link between 2 meteorites, answering 1 meteorite correctly will destroy both meteorites (If 1 meteorite answers incorrectly, you can still answer the remaining question to destroy both)"
                        },
                        new
                        {
                            Id = new Guid("192b995e-9cfa-45ee-9f6f-f6fff5803059"),
                            Code = "GB001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "What kind of bomb sticks like glue?",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Gum Bomp",
                            Usage = "Place the bomb in one location, when the meteorite sticks it will explode, causing the meteorite to stand still for 2 seconds"
                        },
                        new
                        {
                            Id = new Guid("12b08f82-9b0b-4a7a-92d2-10e35b9fea4e"),
                            Code = "HI001",
                            CreatedDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Whose card is this?",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Hacker ID",
                            Usage = "Only use when answering a question, immediately display the answer and answer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
