variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  GIT_STRATEGY: clone

image: mirror.gcr.io/library/docker:stable

services:
- name: mirror.gcr.io/library/docker:stable-dind
  alias: docker

before_script:
  - export CURRENT_TIME=$(date +"%d%m%y")
  - export TAG=auth-openid-$CI_COMMIT_SHORT_SHA-$CURRENT_TIME
  - export IMAGE_VALUES=$CI_COMMIT_SHORT_SHA-$CURRENT_TIME
  - echo $TAG


stages:
- auth-build
- auth-deploy
- cms-build
- cms-deploy
- gateway-build
- gateway-deploy
- hangfire-build
- hangfire-deploy
- interaction-build
- interaction-deploy
- lcms-build
- lcms-deploy
- lms-build
- lms-deploy
- notification-build
- notification-deploy
- ordering-build
- ordering-deploy
- realtime-build
- realtime-deploy
- sender-build
- sender-deploy
- storage-build
- storage-deploy
- system-build
- system-deploy
- training-build
- training-deploy
- user-build
- user-deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "ntdo/feature/auth-openid"'

# AUTH STAGE

auth-build:
  stage: auth-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Auth.Development.Dockerfile -t $CI_REGISTRY_IMAGE/auth:$TAG .
    - docker push $CI_REGISTRY_IMAGE/auth:$TAG
  only:
    changes:
      - Services/Fsel.Identity/**/*

auth-deploy:
  stage: auth-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/auth.yaml
    - kubectl apply -f Deploy/auth.yaml --kubeconfig=config -n fsel-developer
  only: 
    changes:
      - Services/Fsel.Identity/**/*

# CMS SATGE
cms-build:
  stage: cms-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Cms.PlanetDefender.Development.Dockerfile -t $CI_REGISTRY_IMAGE/cms-planetdefender:$TAG .
    - docker push $CI_REGISTRY_IMAGE/cms-planetdefender:$TAG
  only:
    changes:
      - Services/Fsel.Cms.PlanetDefender/**/*

cms-deploy:
  stage: cms-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/cms.yaml
    - kubectl apply -f Deploy/cms.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Cms.PlanetDefender/**/*

# GATEWAY STAGE

gateway-build:
  stage: gateway-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Gateway.Development.Dockerfile -t $CI_REGISTRY_IMAGE/api-gateway:$TAG .
    - docker push $CI_REGISTRY_IMAGE/api-gateway:$TAG
  only:
    changes:
      - Services/Fsel.Gateway/**/*

gateway-deploy:
  stage: gateway-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/gateway.yaml
    - kubectl apply -f Deploy/gateway.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Gateway/**/*

# HANGFIRE STAGE

hangfire-build:
  stage: hangfire-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Hangfire.Development.Dockerfile -t $CI_REGISTRY_IMAGE/hangfire:$TAG .
    - docker push $CI_REGISTRY_IMAGE/hangfire:$TAG
  only:
    changes:
      - Services/Fsel.Hangfire/**/*

hangfire-deploy:
  stage: hangfire-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/hangfire.yaml
    - kubectl apply -f Deploy/hangfire.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Hangfire/**/*

# INTERACTION STAGE

interaction-build:
  stage: interaction-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Interaction.Development.Dockerfile -t $CI_REGISTRY_IMAGE/interaction:$TAG .
    - docker push $CI_REGISTRY_IMAGE/interaction:$TAG
  only:
    changes:
      - Services/Fsel.Interaction/**/*

interaction-deploy:
  stage: interaction-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/interaction.yaml
    - kubectl apply -f Deploy/interaction.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Interaction/**/*

# LCMS STAGE

lcms-build:
  stage: lcms-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Lcms.Development.Dockerfile -t $CI_REGISTRY_IMAGE/lcmsapi:$TAG .
    - docker push $CI_REGISTRY_IMAGE/lcmsapi:$TAG
  only:
    changes:
      - Services/Fsel.Course/**/*

lcms-deploy:
  stage: lcms-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/lcms.yaml
    - kubectl apply -f Deploy/lcms.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Course/**/*

# LMS STAGE

lms-build:
  stage: lms-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Lms.Development.Dockerfile -t $CI_REGISTRY_IMAGE/lmsapi:$TAG .
    - docker push $CI_REGISTRY_IMAGE/lmsapi:$TAG
  only:
    changes:
      - Services/Fsel.Course/**/*

lms-deploy:
  stage: lms-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/lms.yaml
    - kubectl apply -f Deploy/lms.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Course/**/*

# NOTIFICATION STAGE

notification-build:
  stage: notification-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Notification.Development.Dockerfile -t $CI_REGISTRY_IMAGE/notification:$TAG .
    - docker push $CI_REGISTRY_IMAGE/notification:$TAG
  only:
    changes:
      - Services/Fsel.Notification/**/*

notification-deploy:
  stage: notification-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/notification.yaml
    - kubectl apply -f Deploy/notification.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Notification/**/*

# ORDERING STAGE

ordering-build:
  stage: ordering-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Ordering.Development.Dockerfile -t $CI_REGISTRY_IMAGE/ordering:$TAG .
    - docker push $CI_REGISTRY_IMAGE/ordering:$TAG
  only:
    changes:
      - Services/Fsel.Ordering/**/*

ordering-deploy:
  stage: ordering-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/ordering.yaml
    - kubectl apply -f Deploy/ordering.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Ordering/**/*

# REALTIME STAGE

realtime-build:
  stage: realtime-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Realtime.Development.Dockerfile -t $CI_REGISTRY_IMAGE/realtime:$TAG .
    - docker push $CI_REGISTRY_IMAGE/realtime:$TAG
  only:
    changes:
      - Services/Fsel.Realtime/**/*

realtime-deploy:
  stage: realtime-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/realtime.yaml
    - kubectl apply -f Deploy/realtime.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Realtime/**/*

# SENDER STAGE

sender-build:
  stage: sender-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Sender.Development.Dockerfile -t $CI_REGISTRY_IMAGE/sender:$TAG .
    - docker push $CI_REGISTRY_IMAGE/sender:$TAG
  only:
    changes:
      - Services/Fsel.Sender/**/*

sender-deploy:
  stage: sender-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/sender.yaml
    - kubectl apply -f Deploy/sender.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Sender/**/*

# STORAGE STAGE

storage-build:
  stage: storage-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Storage.Development.Dockerfile -t $CI_REGISTRY_IMAGE/storage:$TAG .
    - docker push $CI_REGISTRY_IMAGE/storage:$TAG
  only:
    changes:
      - Services/Fsel.Storage/**/*

storage-deploy:
  stage: storage-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/storage.yaml
    - kubectl apply -f Deploy/storage.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Storage/**/*

# SYSTEM STAGE

system-build:
  stage: system-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/System.Development.Dockerfile -t $CI_REGISTRY_IMAGE/system:$TAG .
    - docker push $CI_REGISTRY_IMAGE/system:$TAG
  only:
    changes:
      - Services/Fsel.System/**/*

system-deploy:
  stage: system-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/system.yaml
    - kubectl apply -f Deploy/system.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.System/**/*

# TRAINING STAGE

training-build:
  stage: training-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/Training.Development.Dockerfile -t $CI_REGISTRY_IMAGE/training:$TAG .
    - docker push $CI_REGISTRY_IMAGE/training:$TAG
  only:
    changes:
      - Services/Fsel.Training/**/*

training-deploy:
  stage: training-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/training.yaml
    - kubectl apply -f Deploy/training.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Training/**/*

# USER STAGE

user-build:
  stage: user-build
  tags:
    - atlantic-k8s
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker login registry.fsel.edu.vn -u tunglinh -p glpat-BosS33r3VPAwzJUK4sYR
    - docker build -f Environments/Development/User.Development.Dockerfile -t $CI_REGISTRY_IMAGE/user:$TAG .
    - docker push $CI_REGISTRY_IMAGE/user:$TAG
  only:
    changes:
      - Services/Fsel.Identity/**/*

user-deploy:
  stage: user-deploy
  tags:
    - atlantic-k8s
  image: bitnami/kubectl
  script:
    - sed -i "s/auth-openid-.............../auth-openid-$IMAGE_VALUES/g" Deploy/user.yaml
    - kubectl apply -f Deploy/user.yaml --kubeconfig=config -n fsel-developer
  only:
    changes:
      - Services/Fsel.Identity/**/*
