apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth
        image: fselacr.azurecr.io/authapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer