<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MMLib.SwaggerForOcelot" Version="6.2.0" />
    <PackageReference Include="Ocelot" Version="18.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.103.51" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.5" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="3.7.0.195" />
    <PackageReference Include="JWT" Version="10.1.1" />
    <PackageReference Include="Fsel.Core" Version="1.2.32-rc.54.25.5.tenant.2" />
  </ItemGroup>
  <!-- Tests -->
  <ItemGroup Label="Tests Packages" Condition="'$(IsTestProject)' == 'true'">
  </ItemGroup>
</Project>
