<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MMLib.SwaggerForOcelot" Version="6.2.0" />
    <PackageReference Include="Ocelot" Version="18.0.0" />

    <PackageReference Include="Fsel.Core" Version="1.0.10" />
  </ItemGroup>
  <!-- Tests -->
  <ItemGroup Label="Tests Packages" Condition="'$(IsTestProject)' == 'true'">
  </ItemGroup>
</Project>
