apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway
        image: gatewayfselacr.azurecr.io/fsel_src
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-svc
spec:
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5200
  type: LoadBalancer