apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interaction-api
  template:
    metadata:
      labels:
        app: interaction-api
    spec:
      containers:
      - name: interaction
        image: fselacr.azurecr.io/interactionapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: interaction-api-svc
spec:
  selector:
    app: interaction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer