apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-api
  template:
    metadata:
      labels:
        app: lms-api
    spec:
      containers:
      - name: lms
        image: lmsfselacr.azurecr.io/fsel_src
        imagePullPolicy: Always
        ports:
        - containerPort: 5204
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: lms-api-svc
spec:
  selector:
    app: lms-api
  ports:
    - protocol: TCP
      port: 5204
      targetPort: 5204
  type: LoadBalancer