apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training-api
  template:
    metadata:
      labels:
        app: training-api
    spec:
      containers:
      - name: training
        image: trainingfselacr.azurecr.io/fsel_src
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: training-api-svc
spec:
  selector:
    app: training-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer