apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-testing
spec:
  selector:
    matchLabels:
      app: interaction-testing
  replicas: 1
  template:
    metadata:
      labels:
        app: interaction-testing
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node_role
                operator: In
                values:
                - appnodes-staging
      containers:
      - name: interaction-testing
        image: registry.fsel.edu.vn/fsel/api/fsel_src/interaction:..........
        ports:
        - containerPort: 80
        - containerPort: 443 
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 30m
            memory: 50Mi
        volumeMounts:
        - mountPath: /app/appsettings.Testing.json
          name: interaction-appsettings-testing
          subPath: appsettings.Testing.json
      imagePullSecrets:
        - name: gitlab-fsel-secret
      volumes:
      - configMap:
          defaultMode: 420
          name: interaction-appsettings-testing
        name: interaction-appsettings-testing

---
apiVersion: v1
kind: Service
metadata:
  name: interaction-testing
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: interaction-testing


