<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsUseCore>true</IsUseCore>
    <IsUseOpenId>true</IsUseOpenId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Queries\**" />
    <EmbeddedResource Remove="Models\Queries\**" />
    <None Remove="Models\Queries\**" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Packages\IdentityServer\AspNetIdentity\src\IdentityServer4.AspNetIdentity.csproj" />
    <ProjectReference Include="..\..\..\Packages\IdentityServer\EntityFramework.Storage\src\IdentityServer4.EntityFramework.Storage.csproj" />
    <ProjectReference Include="..\..\..\Packages\IdentityServer\EntityFramework\src\IdentityServer4.EntityFramework.csproj" />
    <ProjectReference Include="..\..\..\Packages\IdentityServer\IdentityServer4\src\IdentityServer4.csproj" />
    <ProjectReference Include="..\..\..\Packages\IdentityServer\Storage\src\IdentityServer4.Storage.csproj" />
    <ProjectReference Include="..\..\Shared\Fsel.Shared\Fsel.Shared.csproj" />
  </ItemGroup>

</Project>
