<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Queries\**" />
    <EmbeddedResource Remove="Models\Queries\**" />
    <None Remove="Models\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Models\CommandModels\Human\" />
    <Folder Include="Models\CommandModels\Parents\" />
    <Folder Include="Models\CommandModels\Students\" />
    <Folder Include="Models\QueryModels\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Fsel.Core\Fsel.Core.csproj" />
  </ItemGroup>

</Project>
