apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-production
spec:
  selector:
    matchLabels:
      app: auth-production
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-production
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node_role
                operator: In
                values:
                - appnodes-prod
      containers:
      - name: auth-production
        image: registry.fsel.edu.vn/fsel/api/fsel_src/auth:..........
        ports:
        - containerPort: 80
        - containerPort: 443 
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 30m
            memory: 50Mi
        volumeMounts:
        - mountPath: /app/appsettings.Production.json
          name: auth-appsettings-production
          subPath: appsettings.Production.json
      imagePullSecrets:
        - name: gitlab-fsel-secret
      tolerations:
      - effect: NoSchedule
        key: appnodes-prod
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: auth-appsettings-production
        name: auth-appsettings-production

---
apiVersion: v1
kind: Service
metadata:
  name: auth-production
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: auth-production


