// Copyright (c) Atlantic. All rights reserved.

namespace Fsel.Shared.Enums
{
    public enum EnumNotificationContent
    {
        FlagClassForum,
        OrderChangeStatus,
        OrderCreate,
        CreateClassForumResult,
        Comment,
        ReplyComment,
        FlagComment,
        DeleteClassForumResult,
        DeleteComment,
        LikeComment,
        LikeClassForum,
        AIFeedBack,
        ChangeClassLiveTeacher,
        MockTest,
        FullMockTest,
        ReviewFsel,
        DiscussionBoardInActive,
        LeaderBoard,
        ApprovePostClassForum,
        RejectApprovalPostClassForum,
        NoticePayment,
        NoticeExpireAfterTwoWeek,
        NoticeExpireAfterTwoDay,
        CommentPost,
        LikePost,
        ReplyCommentPost,
        CourseChange,
        LuckyTicket,
        FselFlowFBEvent,

        //Version 1.1
        CompletedStreakLogin,

        CompleteCourse,
        UpgradeOrder,
        SubcriptionNotice,
        NoticeTrialExpired,
        PlanWeekExtend,
        PlanDayExtend,
        ExtendSuccessfully,
        FirstStudyNotice,
        SecondStudyNotice,
        ThirdStudyNotice,
        FourthStudyNotice,
        FifthStudyNotice,
        StopBothering,
        TreasureExploration,
        EnergyCollecting,
        FriendCompletedExam,
        FriendCompleteUnitOne,
        FriendPaymentSuccessfully,
        RecallCoinSurvey,
        SurveyReward,
        IllegalCoinRecall,
        AddCoinBuyCourse,
        NullForbiddenClassForum,
        ForbiddenClassForum,
        LanguageNotEnglish,
        SurveyAssignment
    }
}
