<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Migrations\DataProtectionKey\" />
    <Folder Include="ServiceModels\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.Identity.Domain\Fsel.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
