apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangfire-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangfire-api
  template:
    metadata:
      labels:
        app: hangfire-api
    spec:
      containers:
      - name: hangfire
        image: fselacr.azurecr.io/hangfireapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: hangfire-api-svc
spec:
  selector:
    app: hangfire-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer