apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sender-api
  template:
    metadata:
      labels:
        app: sender-api
    spec:
      containers:
      - name: sender
        image: fselacr.azurecr.io/senderapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: sender-api-svc
spec:
  selector:
    app: sender-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer