apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user
        image: fselacr.azurecr.io/userapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer