// <auto-generated />
using System;
using Fsel.System.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fsel.System.Infrastructure.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20230927132900_Create_GameVocabularyTable_And_GameCenterTable")]
    partial class Create_GameVocabularyTable_And_GameCenterTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fsel.System.Domain.Entities.Configs.CourseTimeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<int>("DurationMonth")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("CourseTimeConfigs");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.FeatureAccessTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<long>("AccessTime")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("EnumFeature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("LastVisited")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<int>("Visit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeatureAccessTimes");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.ForbiddenWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<string>("Word")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ForbiddenWords");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("GameCenters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9c55ef5-01e0-4fa6-b68a-3aaea1089548"),
                            CreatedDate = new DateTime(2023, 9, 27, 20, 28, 59, 971, DateTimeKind.Local).AddTicks(8393),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "Planet Defender Parameters"
                        });
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("CourseLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("GameTopics");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameVocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("AlternateSpellingStr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Antonym")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CefrLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CourseLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<string>("Definition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("GameCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PartSpeech")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneticTranscription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Synonym")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UnitOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<string>("UsEquivalent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("WordCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameCenterId");

                    b.HasIndex("WordCategoryId");

                    b.ToTable("GameVocabularies");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.LiveTimeFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<double?>("EndTime")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<double?>("StartTime")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("LiveTimeFrames");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.LogAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("FunctionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("RecordIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("LogActions");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.QuestBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsLifeTime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("NumberOfStars")
                        .HasColumnType("int");

                    b.Property<string>("PackageIdsStr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("QuestBoards");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.QuestBoardConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("QuestBoardConfigs");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.QuestBoardStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("QuestBoardId");

                    b.ToTable("QuestBoardStudents");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.ReferralDiscountConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<int>("IndexNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("RecevicerDiscountType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("RecevierDiscountValue")
                        .HasColumnType("float");

                    b.Property<string>("SenderDiscountType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("SenderDiscountValue")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("ReferralDiscountConfigs");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.TeachingCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("CourseLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<double>("LiveLessonCost")
                        .HasColumnType("float");

                    b.Property<double>("SpeapkingCost")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<double>("WritingCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TeachingCosts");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameVocabulary", b =>
                {
                    b.HasOne("Fsel.System.Domain.Entities.GameCenter", "GameCenter")
                        .WithMany("GameVocabularies")
                        .HasForeignKey("GameCenterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fsel.System.Domain.Entities.GameTopic", "GameTopic")
                        .WithMany("GameVocabularies")
                        .HasForeignKey("WordCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GameCenter");

                    b.Navigation("GameTopic");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.QuestBoardStudent", b =>
                {
                    b.HasOne("Fsel.System.Domain.Entities.QuestBoard", "QuestBoard")
                        .WithMany("QuestBoardStudents")
                        .HasForeignKey("QuestBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestBoard");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameCenter", b =>
                {
                    b.Navigation("GameVocabularies");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.GameTopic", b =>
                {
                    b.Navigation("GameVocabularies");
                });

            modelBuilder.Entity("Fsel.System.Domain.Entities.QuestBoard", b =>
                {
                    b.Navigation("QuestBoardStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
