apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-dev
spec:
  selector:
    matchLabels:
      app: cms-dev
  replicas: 1 
  template:
    metadata:
      labels:
        app: cms-dev
    spec:
      containers:
      - name: cms-dev
        image: registry.fsel.edu.vn/fsel/api/fsel_src/cms-planetdefender:auth-openid-...............
        ports:
        - containerPort: 80
        - containerPort: 443 
      imagePullSecrets:
        - name: dev-image-secret

---
apiVersion: v1
kind: Service
metadata:
  name: cms-dev
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: cms-dev

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms-dev
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Timeline,IdToken,X-Token,X-Time,Client-ID,Token,formdata"
#    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Range"
spec:
  ingressClassName: nginx-public
  rules:
  - host: fsel-cms-dev.fsel.edu.vn
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: cms-dev
            port:
              number: 80
  tls:
  - hosts:
    - fsel-cms-dev.fsel.edu.vn
    secretName: fsel-cms-dev.fsel.edu.vn-wildcard

status:
  loadBalancer:
    ingress:
    - hostname: 103.22.218.217.nip.io


