apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-dev
spec:
  selector:
    matchLabels:
      app: system-dev
  replicas: 1 
  template:
    metadata:
      labels:
        app: system-dev
    spec:
      containers:
      - name: fsel-system-testing
        image: registry.fsel.edu.vn/fsel/api/fsel_src/system:auth-openid-...............
        ports:
        - containerPort: 80
        - containerPort: 443 
      imagePullSecrets:
        - name: dev-image-secret

---
apiVersion: v1
kind: Service
metadata:
  name: system-dev
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: system-dev

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-dev
  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#    nginx.ingress.kubernetes.io/x-forwarded-proto: "https"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,systemorization,Timeline,IdToken,X-Token,X-Time,Client-ID,Token,formdata"
spec:
  ingressClassName: nginx-public
  rules:
  - host: fsel-system-dev.fsel.edu.vn
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: system-dev
            port:
              number: 80
#  tls:
#  - hosts:
#    - fsel-system-dev.fsel.edu.vn
#    secretName: fsel-system-dev.fsel.edu.vn-wildcard

status:
  loadBalancer:
    ingress:
    - hostname: 103.22.218.217.nip.io
