trigger:
  branches:
    include:
    - staging
  paths:
    include:
    - Services/Fsel.System/*
    - Services/Shared/*
    - System.Staging.Dockerfile

 
pool:
  vmImage: 'ubuntu-latest'

 
variables:
  dockerRegistryServiceConnection: 'fsel'
  containerRegistry: 'fselacr.azurecr.io'
  repository: 'systemapi'
  dockerfile: 'System.Staging.Dockerfile'
  currentdate: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  #tag: '$(Build.SourceBranchName)-$(shortCommitSha)-$(currentdate)'

 
stages:
  - stage: build_image_docker
    displayName: Build and push image
    jobs:  
    - job: Build
      displayName: Build
      steps:
      - script: |
          SHORT_COMMIT_SHA=$(echo $(Build.SourceVersion) | cut -c1-8)
          echo "##vso[task.setvariable variable=shortCommitSha]${SHORT_COMMIT_SHA}"
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(repository)
          dockerfile: $(dockerfile)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(Build.SourceBranchName)-$(shortCommitSha)-$(currentdate)