<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.Course.Infrastructure\Fsel.Course.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\ClassForumCmd\" />
    <Folder Include="Events\" />
    <Folder Include="Queues\Publishers\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Queries\AiPromptManagerQuery\GetAiPromptChidManagerQuery.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Queries\AiPromptManagerQuery\GetAiCriteriaByIdAipromptQuery.cs" />
    <Compile Remove="Queries\AiPromptManagerQuery\GetAiPromptChidManagerQuery.cs" />
  </ItemGroup>

</Project>
