<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.User.Common\Fsel.User.Common.csproj" />
    <ProjectReference Include="..\Fsel.User.Domain\Fsel.User.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configs\" />
    <Folder Include="Maps\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
