// <auto-generated />
using System;
using Fsel.Notification.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fsel.Notification.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationsDBContext))]
    [Migration("20240910091156_UpdateNotificationTypev10")]
    partial class UpdateNotificationTypev10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationMessages");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationMessageTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("NotificationMessageId");

                    b.ToTable("NotificationMessageTranslations");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationRemind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NotificationReminds");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TemplateLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d789788a-1ba5-405b-b280-ae92cd3b4fc2"),
                            Content = "FlagClassForum",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/{0}?courseId={1}&unitId={0}&type=classForum&classForumResultId={2}",
                            TemplateMessage = "Bài viết của {0} thuộc {1} đã bị gán cờ. Vui lòng kiểm tra.",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("e89b5850-33ff-4922-89e1-1a2f7de29375"),
                            Content = "CreateClassForumResult",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/class-forum-management",
                            TemplateMessage = "Bạn có bài đăng của học sinh đang chờ duyệt.",
                            Type = "Text"
                        },
                        new
                        {
                            Id = new Guid("efba1f99-8fad-47b5-af14-978f674f438e"),
                            Content = "FlagComment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/{0}?courseId={1}&unitId={0}&type=classForum&classForumResultId={2}&commentId={3}",
                            TemplateMessage = "Bình luận của {0} thuộc {1} đã bị gán cờ. Vui lòng kiểm tra.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("810c70ca-4f3c-4d02-a194-708fa45d42ea"),
                            Content = "Comment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}/class-forum/{3}?page=class-forum",
                            TemplateMessage = "{0} vừa bình luận bài viết của bạn.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("10c2d5f8-1316-45e4-8fa1-e512ec1510c0"),
                            Content = "CommentPost",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "{0} vừa bình luận bài viết của bạn.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("b09fa1f2-3936-4e52-aa9c-d3a354f1c566"),
                            Content = "LikePost",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "{0} vừa thích bài viết của bạn.",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("6a55c6bd-0494-4fe9-8a72-911210c8a215"),
                            Content = "ReplyCommentPost",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "{0} vừa trả lời bình luận của bạn.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("9e983172-dba2-4ca7-b602-372c011ecb99"),
                            Content = "ReplyComment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}/class-forum/{3}?page=class-forum-user",
                            TemplateMessage = "{0} vừa trả lời bình luận của bạn.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("cd8a1edb-029f-4b2d-9725-c796e6fd7e5b"),
                            Content = "OrderChangeStatus",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn",
                            TemplateMessage = "Bạn đã mua gói {0} thành công. Hãy bắt đầu học nào!",
                            Type = "Text"
                        },
                        new
                        {
                            Id = new Guid("3881403a-d412-4593-aee5-5a38f4e078f9"),
                            Content = "OrderCreate",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/payment",
                            TemplateMessage = "Bạn có hóa đơn khóa học mới phê duyệt. Nhấn để phê duyệt.",
                            Type = "Text"
                        },
                        new
                        {
                            Id = new Guid("27007edb-25d8-493e-84d8-85f6f9e165b2"),
                            Content = "DeleteComment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}/class-forum/{3}?page=class-forum",
                            TemplateMessage = "Bình luận của bạn trong bài viết của {0} đã bị gỡ do vi phạm tiêu chuẩn cộng đồng của FSEL.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("57c709a6-03bd-4a3f-ad34-f9449587e1df"),
                            Content = "DeleteClassForumResult",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}?page=class-forum",
                            TemplateMessage = "Bài viết của bạn trong {0} đã bị gỡ do vi phạm tiêu chuẩn cộng đồng của FSEL. Vui lòng thử lại!",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("810c70ca-4f3c-4d02-a491-708fa45d42ea"),
                            Content = "LikeClassForum",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}/class-forum/{3}?page=class-forum",
                            TemplateMessage = "{0} đã thích bài viết của bạn.",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("3ad02de7-a8a8-4db6-8286-486c81390ed3"),
                            Content = "LikeComment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/{0}?courseId={1}&unitId={0}&type=classForum&classForumResultId={2}&commentId={3}",
                            TemplateMessage = "{0} đã thích bình luận của bạn.",
                            Type = "LinkComment"
                        },
                        new
                        {
                            Id = new Guid("59942527-ca1f-4f18-a66b-cdcfe87b317e"),
                            Content = "AIFeedBack",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/lesson/{0}?courseId={1}&unitId={2}?type=aiFeedback",
                            TemplateMessage = "Bài đăng của bạn đã được chấm bởi hệ thống AI ChatGPT. Nhấn để xem chi tiết",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("4b5173d1-3d0b-4df6-b3ca-15cd175926a1"),
                            Content = "ChangeClassLiveTeacher",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "Buổi {0} diễn ra vào ngày {1} đã thay đổi giáo viên",
                            Type = "LinkPopup"
                        },
                        new
                        {
                            Id = new Guid("85062a12-ab5b-486c-a8ab-db329ea7f46d"),
                            Content = "MockTest",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/mock-test-report?sectionGroupId={0}&mockTestResultId={1}&courseId={2}&unitId={3}",
                            TemplateMessage = "Bài {0} đã được giáo viên chấm điểm. Nhấn để xem chi tiết",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("46526095-5284-46f0-8c86-e00d95f1c985"),
                            Content = "FullMockTest",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/learn/full-mock-test/{0}?courseId={1}",
                            TemplateMessage = "Bài {0} đã được giáo viên chấm điểm. Nhấn để xem chi tiết",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("1a7f9999-79e2-4eb1-85a8-cc8d1398f732"),
                            Content = "ReviewFsel",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/review",
                            TemplateMessage = "Hãy chia sẻ cảm nhận của bạn về LMS!",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("59bc5071-1ef7-4362-9bb0-8848bb6f8ced"),
                            Content = "DiscussionBoardInActive",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "Bay! Bay cao! Bay xa! Hãy cùng khám phá với các bạn trên khắp thế giới qua Diễn đàn chung nào!",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("9da28757-2d28-40cb-b88c-cc51fc15bb43"),
                            Content = "LeaderBoard",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/home",
                            TemplateMessage = "Chúc mừng bạn đã đạt top {0} trên Bảng xếp hạng!",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("69cc9e39-82d5-4d1a-81b9-8c97ec54bfad"),
                            Content = "ApprovePostClassForum",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}/class-forum/{3}?page=class-forum",
                            TemplateMessage = "Bài đăng của bạn đã được phê duyệt. Nhấn để xem chi tiết",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("75540141-a6d9-409d-a3ce-90c9a7577e8a"),
                            Content = "RejectApprovalPostClassForum",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "learn/{0}/{1}/lesson/{2}?page=class-forum",
                            TemplateMessage = "Bài viết của bạn trong {0} đã bị từ chối phê duyệt do vi phạm tiêu chuẩn cộng đồng của FSEL. Vui lòng thử lại!",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("05441907-46a9-4178-9a69-fce295d670be"),
                            Content = "NoticePayment",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/pricing-plan",
                            TemplateMessage = "Thời gian học thử của bạn sẽ kết thúc trong vòng 2 ngày tới. Bạn vui lòng gia hạn khóa học để đảm bảo tiếp tục hành trình học tập mà không bị gián đoạn nhé",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("f9d5a75f-fd55-4b1e-ade8-a446b6465e34"),
                            Content = "NoticeExpireAfterTwoWeek",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/pricing-plan",
                            TemplateMessage = "Khóa học của bạn sẽ kết thúc trong 2 tuần tới.Bạn vui lòng gia hạn khóa học để đảm bảo tiếp tục hành trình học tập mà không bị gián đoạn nhé",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("a99bfaae-4139-4766-9405-ef24332fb51a"),
                            Content = "NoticeExpireAfterTwoDay",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "/pricing-plan",
                            TemplateMessage = "Khóa học của bạn sẽ kết thúc trong 2 ngày tới.Bạn vui lòng gia hạn khóa học để đảm bảo tiếp tục hành trình học tập mà không bị gián đoạn nhé",
                            Type = "LinkPage"
                        },
                        new
                        {
                            Id = new Guid("6f75034f-4d9b-4471-b5a4-a226979b5ab3"),
                            Content = "CourseChange",
                            CreatedDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Icon = "",
                            IsDeleted = false,
                            Priority = 1,
                            TemplateLink = "",
                            TemplateMessage = "Yay! Bạn đã đổi trình độ sang khóa học {0} thành công! Hãy cùng Techie và Fsel bắt đầu hành trình học tập thú vị ngay thôi nào!",
                            Type = "LinkPage"
                        });
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationTypeTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationTypeTranslations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02dc26ac-2d45-4983-b0e8-15b4c7cb8b90"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a194-708fa45d42ea"),
                            TemplateMessage = "{0} vừa bình luận bài viết của bạn."
                        },
                        new
                        {
                            Id = new Guid("678236d5-543b-4dd1-ab99-c2caa99a62af"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a194-708fa45d42ea"),
                            TemplateMessage = "{0} has just commented on your post."
                        },
                        new
                        {
                            Id = new Guid("0489ba9d-222f-4bea-ae35-3d8ac36cb35f"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a194-708fa45d42ea"),
                            TemplateMessage = "{0} vient de commenter votre publication."
                        },
                        new
                        {
                            Id = new Guid("0d199223-e152-4a39-9b22-c0a510033e14"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("9e983172-dba2-4ca7-b602-372c011ecb99"),
                            TemplateMessage = "{0} vừa trả lời bình luận của bạn."
                        },
                        new
                        {
                            Id = new Guid("77c8859e-37c0-4ce9-8bf0-d9aa2cec1d43"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("9e983172-dba2-4ca7-b602-372c011ecb99"),
                            TemplateMessage = "{0} has just replied to your comment."
                        },
                        new
                        {
                            Id = new Guid("dbfdb359-cd76-443d-94c1-c73888957d56"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("9e983172-dba2-4ca7-b602-372c011ecb99"),
                            TemplateMessage = "{0} vient de répondre à votre commentaire."
                        },
                        new
                        {
                            Id = new Guid("973b9f47-3bb6-4ecc-8a4f-e6482c6fb80e"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("cd8a1edb-029f-4b2d-9725-c796e6fd7e5b"),
                            TemplateMessage = "Bạn đã mua gói {0} thành công. Hãy bắt đầu học nào!"
                        },
                        new
                        {
                            Id = new Guid("e8d53f67-68ee-4352-b134-ab47d6e9768c"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("cd8a1edb-029f-4b2d-9725-c796e6fd7e5b"),
                            TemplateMessage = "You have successfully purchased the {0} package. Let's start learning!"
                        },
                        new
                        {
                            Id = new Guid("f5560aac-3ac4-4a88-9d84-a82800e1b149"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("cd8a1edb-029f-4b2d-9725-c796e6fd7e5b"),
                            TemplateMessage = "Vous avez acheté avec succès le forfait {0}. Commençons à apprendre !"
                        },
                        new
                        {
                            Id = new Guid("876495b2-1756-4cb3-8a68-2261221a89ad"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("27007edb-25d8-493e-84d8-85f6f9e165b2"),
                            TemplateMessage = "Bình luận của bạn trong bài viết của {0} đã bị gỡ do vi phạm tiêu chuẩn cộng đồng của FSEL."
                        },
                        new
                        {
                            Id = new Guid("efb6b960-c668-4643-b433-93142da84ad3"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("27007edb-25d8-493e-84d8-85f6f9e165b2"),
                            TemplateMessage = "Your comment on {0}'s post has been removed because it violated FSEL's community standards."
                        },
                        new
                        {
                            Id = new Guid("72c38c36-fc6b-4ed6-a8e6-fc711903b5af"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("27007edb-25d8-493e-84d8-85f6f9e165b2"),
                            TemplateMessage = "Votre commentaire sur la publication de {0} a été supprimé car il enfreignait les normes de la communauté FSEL."
                        },
                        new
                        {
                            Id = new Guid("dff468cf-a150-4685-b7ba-fa2d4eeb2b05"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("57c709a6-03bd-4a3f-ad34-f9449587e1df"),
                            TemplateMessage = "Bài viết của bạn trong {0} đã bị gỡ do vi phạm tiêu chuẩn cộng đồng của FSEL. Vui lòng thử lại!"
                        },
                        new
                        {
                            Id = new Guid("d095d2c0-2266-4765-b4d4-2da0c685336f"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("57c709a6-03bd-4a3f-ad34-f9449587e1df"),
                            TemplateMessage = "Your post in {0} has been removed for violating FSEL's community standards. Please try again!"
                        },
                        new
                        {
                            Id = new Guid("9bfd2b9d-eb69-4a3b-8788-6526e1b4d784"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("57c709a6-03bd-4a3f-ad34-f9449587e1df"),
                            TemplateMessage = "Votre publication dans {0} a été supprimée pour non-respect des normes de la communauté FSEL. Veuillez réessayer !"
                        },
                        new
                        {
                            Id = new Guid("dc5dd6e3-41d5-4221-b5ff-04035926cf7d"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a491-708fa45d42ea"),
                            TemplateMessage = "{0} đã thích bài viết của bạn."
                        },
                        new
                        {
                            Id = new Guid("782036f2-e5e3-4a36-b8ea-484c7c1db06c"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a491-708fa45d42ea"),
                            TemplateMessage = "{0} has liked your post!"
                        },
                        new
                        {
                            Id = new Guid("48853c68-df32-4ba2-af20-73d47260655d"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("810c70ca-4f3c-4d02-a491-708fa45d42ea"),
                            TemplateMessage = "{0} a aimé votre publication !"
                        },
                        new
                        {
                            Id = new Guid("d8977047-e977-4772-a3e0-c20cb0bc76e3"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("59942527-ca1f-4f18-a66b-cdcfe87b317e"),
                            TemplateMessage = "Bài đăng của bạn đã được chấm bởi hệ thống AI ChatGPT. Nhấn để xem chi tiết"
                        },
                        new
                        {
                            Id = new Guid("760bcc15-6445-4302-b59f-07a3d4c5337a"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("59942527-ca1f-4f18-a66b-cdcfe87b317e"),
                            TemplateMessage = "Your submission has been graded by FSEL's AI. Click to view the results."
                        },
                        new
                        {
                            Id = new Guid("abab8049-4c5d-44c7-93dc-bca5416fc87e"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("59942527-ca1f-4f18-a66b-cdcfe87b317e"),
                            TemplateMessage = "Votre soumission a été notée par l'IA de FSEL. Cliquez pour voir les résultats."
                        },
                        new
                        {
                            Id = new Guid("39ddf48b-b3bb-4898-91e0-54451a4accd0"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("9da28757-2d28-40cb-b88c-cc51fc15bb43"),
                            TemplateMessage = "Chúc mừng bạn đã đạt top {0} trên Bảng xếp hạng!"
                        },
                        new
                        {
                            Id = new Guid("61a570d9-f58d-4278-863f-120680ef789b"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("9da28757-2d28-40cb-b88c-cc51fc15bb43"),
                            TemplateMessage = "Congratulations on reaching top {0} on the Leaderboard!"
                        },
                        new
                        {
                            Id = new Guid("1dc3d61c-00f1-434a-9700-5a1adc423745"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("9da28757-2d28-40cb-b88c-cc51fc15bb43"),
                            TemplateMessage = "Félicitations pour avoir atteint le top {0} du classement !"
                        },
                        new
                        {
                            Id = new Guid("66de6e9c-0c63-4bad-b5e4-c52cafe2bb7f"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("69cc9e39-82d5-4d1a-81b9-8c97ec54bfad"),
                            TemplateMessage = "Bài đăng của bạn đã được phê duyệt. Nhấn để xem chi tiết"
                        },
                        new
                        {
                            Id = new Guid("a5609e92-e166-46ec-ad23-2c0222fcb351"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("69cc9e39-82d5-4d1a-81b9-8c97ec54bfad"),
                            TemplateMessage = "Your post has been approved. Click to view more details."
                        },
                        new
                        {
                            Id = new Guid("5a5954c6-b3f4-4018-8bf2-7134e09ea540"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("69cc9e39-82d5-4d1a-81b9-8c97ec54bfad"),
                            TemplateMessage = "Votre publication a été approuvée. Cliquez pour voir plus de détails."
                        },
                        new
                        {
                            Id = new Guid("561ea827-f02c-49a8-9ea7-240994cfb8cd"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("75540141-a6d9-409d-a3ce-90c9a7577e8a"),
                            TemplateMessage = "Bài viết của bạn trong {0} đã bị từ chối phê duyệt do vi phạm tiêu chuẩn cộng đồng của FSEL. Vui lòng thử lại!"
                        },
                        new
                        {
                            Id = new Guid("de49fb73-928f-418c-a8bc-58d843ff0d42"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("75540141-a6d9-409d-a3ce-90c9a7577e8a"),
                            TemplateMessage = "Your post in {0} has been denied due to violating FSEL's community standards. Please try again!"
                        },
                        new
                        {
                            Id = new Guid("e43e20b2-ed0a-4353-9e44-faa7ad0f2bf0"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("75540141-a6d9-409d-a3ce-90c9a7577e8a"),
                            TemplateMessage = "Votre publication dans {0} a été refusée en raison de la violation des normes de la communauté FSEL. Veuillez réessayer !"
                        },
                        new
                        {
                            Id = new Guid("d114228f-71cb-4607-b50d-b0992e28c270"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "vi-VN",
                            NotificationTypeId = new Guid("6f75034f-4d9b-4471-b5a4-a226979b5ab3"),
                            TemplateMessage = "Yay! Bạn đã đổi trình độ sang khóa học {0} thành công! Hãy cùng Techie và Fsel bắt đầu hành trình học tập thú vị ngay thôi nào!"
                        },
                        new
                        {
                            Id = new Guid("063795cd-d905-4097-8c3b-979c6830f5b0"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "en-US",
                            NotificationTypeId = new Guid("6f75034f-4d9b-4471-b5a4-a226979b5ab3"),
                            TemplateMessage = "Yay! You've successfully changed your level to the {0} course! Let's join Techie and Fsel to start this exciting learning journey now!"
                        },
                        new
                        {
                            Id = new Guid("6a98a753-d5d0-4296-a082-6c9d2df66a70"),
                            CreatedDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Language = "fr-FR",
                            NotificationTypeId = new Guid("6f75034f-4d9b-4471-b5a4-a226979b5ab3"),
                            TemplateMessage = "Yay! Vous avez réussi à changer votre niveau pour le cours {0} ! Rejoignons Techie et Fsel pour commencer ce voyage d'apprentissage passionnant maintenant"
                        });
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationMessage", b =>
                {
                    b.HasOne("Fsel.Notification.Domain.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationMessageTranslation", b =>
                {
                    b.HasOne("Fsel.Notification.Domain.Entities.NotificationMessage", "NotificationMessage")
                        .WithMany("Translations")
                        .HasForeignKey("NotificationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationMessage");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationTypeTranslation", b =>
                {
                    b.HasOne("Fsel.Notification.Domain.Entities.NotificationType", "NotificationType")
                        .WithMany("Translations")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationMessage", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Fsel.Notification.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
