// Copyright (c) Atlantic. All rights reserved.

namespace Fsel.Shared.Constants
{
    public static class HtmlSetting
    {
        public const string Skill = "<div style=\"width:100%\">\r\n                                    <div style=\"display:flex;margin-top:26px\">\r\n                                        <div style=\"display:flex;width:100%\">\r\n                                            \r\n                                            <div style=\"width:15%\">\r\n                                                <img src=\"{0}\"\r\n                                                     alt=\"\" class=\"CToWUd\" data-bit=\"iit\">\r\n                                            </div>\r\n                                            <div style=\"width: 45%;margin-right:5%\">\r\n                                                <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:14px;font-style:normal;font-weight:600;line-height:20px;margin-bottom:6px;width:100%\">\r\n                                                    {1}\r\n                                                </div>\r\n                                                <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:14px;font-style:normal;font-weight:600;line-height:20px;width:100%\">\r\n                                                    <div style=\"width:100%;display:flex\">\r\n                                                        <div style=\"width:{2}%;display:flex;height:10px;border-radius:100px 0 0 100px;background:#53bf65\">\r\n                                                        </div>\r\n                                                        <div style=\"display:flex;width:{3}%;height:10px;border-radius:0 100px 100px 0;background:#e2e4e9\">\r\n                                                        </div>\r\n                                                    </div>\r\n                                                </div>\r\n                                            </div>\r\n                                            <div style=\"display:flex;padding:14px 10px;border-radius:8px;border:1px solid #809fe5;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:16px;font-style:normal;font-weight:400;line-height:24px;width: 22%;\">\r\n                                                <div style=\"margin:0 11px;text-align: center;width: 100%;\">\r\n                                                    <span style=\"text-align:center;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:12px;font-style:normal;font-weight:400;line-height:35px\">\r\n                                                        {4}%\r\n                                                    </span>\r\n                                                </div>\r\n                                            </div>\r\n                                        </div>\r\n                                    </div>\r\n                                </div>";

        public const string Skill1 = "<div style=\"width: 100%\">\r\n    <div style=\"\r\nmargin-bottom: 26px;\r\nwidth: 100%;\r\ntext-align: center;\r\n\">\r\n        <div style=\"width: 100%\">\r\n            <div style=\"\r\nmargin-bottom: 26px;\r\nwidth: 100%;\r\ntext-align: center;\r\n\">\r\n                \r\n\r\n                <div style=\"display: flex; margin-top: 26px\">\r\n                    <div style=\"display: flex; width: 100%\">\r\n\r\n                        <div style=\"width: 10%;\">\r\n                            <img src=\"{0}\" alt=\"\" class=\"CToWUd\" data-bit=\"iit\">\r\n                        </div>\r\n                        <div style=\"width: 60%;margin-right: 5%\">\r\n                            <div style=\"\r\ndisplay: flex;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 18px;\r\nfont-style: normal;\r\nfont-weight: 600;\r\nline-height: 20px;\r\nmargin-bottom: 6px;\r\nwidth: 100%;\r\n\">\r\n                                {1}\r\n                            </div>\r\n                            <div style=\"\r\ndisplay: flex;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 18px;\r\nfont-style: normal;\r\nfont-weight: 600;\r\nline-height: 20px;\r\nwidth: 100%;\r\n\">\r\n                                <div style=\"width: 100%; display: flex\">\r\n                                    <div style=\"\r\nwidth: {2}%;\r\ndisplay: flex;\r\nheight: 10px;\r\nborder-radius: 100px 0 0 100px;\r\nbackground: #53bf65;\r\n\"></div>\r\n                                    <div style=\"\r\ndisplay: flex;\r\nwidth: {3}%;\r\nheight: 10px;\r\nborder-radius: 0 100px 100px 0;\r\nbackground: #e2e4e9;\r\n\"></div>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div style=\"\r\npadding: 14px 10px;\r\nborder-radius: 8px;\r\nborder: 1px solid #809fe5;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 20px;\r\nfont-style: normal;\r\nfont-weight: 400;\r\nline-height: 24px;\r\nwidth: 20%;\r\ntext-align: center;\r\n\">\r\n                            <div style=\"margin: 0 11px;\">\r\n                                <span style=\"\r\ntext-align: center;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 12px;\r\nfont-style: normal;\r\nfont-weight: 400;\r\nline-height: 35px;\r\n\">\r\n                                    {4}%\r\n                                </span>\r\n                            </div>\r\n\r\n                            \r\n\r\n                            \r\n                            \r\n                        </div>\r\n                    </div>\r\n                </div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>";

        public const string CompareSkill = "<div style=\"display: flex; margin-top: 26px\">\r\n    <div style=\"display: flex; width: 100%\">\r\n\r\n        <div style=\"width: 10%;\">\r\n            <img src=\"{0}\" alt=\"\" class=\"CToWUd\" data-bit=\"iit\">\r\n        </div>\r\n        <div style=\"width: 60%;margin-right: 5%\">\r\n            <div style=\"\r\ndisplay: flex;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 18px;\r\nfont-style: normal;\r\nfont-weight: 600;\r\nline-height: 20px;\r\nmargin-bottom: 6px;\r\nwidth: 100%;\r\n\">\r\n               {1}\r\n            </div>\r\n            <div style=\"\r\ndisplay: flex;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 18px;\r\nfont-style: normal;\r\nfont-weight: 600;\r\nline-height: 20px;\r\nwidth: 100%;\r\n\">\r\n                <div style=\"width: 100%; display: flex\">\r\n                    <div style=\"\r\nwidth: {2}%;\r\ndisplay: flex;\r\nheight: 10px;\r\nborder-radius: 100px 0 0 100px;\r\nbackground: #53bf65;\r\n\"></div>\r\n                    <div style=\"\r\ndisplay: flex;\r\nwidth: {3}%;\r\nheight: 10px;\r\nborder-radius: 0 100px 100px 0;\r\nbackground: #e2e4e9;\r\n\"></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div style=\"\r\ndisplay: flex;\r\npadding: 14px 10px;\r\nborder-radius: 8px;\r\nborder: 1px solid #809fe5;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 20px;\r\nfont-style: normal;\r\nfont-weight: 400;\r\nline-height: 24px;\r\nwidth: 20%;\r\n\">\r\n            <div style=\"margin: 0 11px; display: flex\">\r\n                <span style=\"\r\ntext-align: center;\r\ncolor: #3a4b78;\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 12px;\r\nfont-style: normal;\r\nfont-weight: 400;\r\nline-height: 35px;\r\n\">\r\n                    {4}%\r\n                </span>\r\n            </div>\r\n\r\n            <div style=\"\r\nwidth: 1px;\r\nheight: 35px;\r\nbackground: #809fe5;\r\nmargin: 0 5px;\r\n\"></div>\r\n\r\n            <span style=\"\r\nbackground: #cc666f;\r\nbackground-clip: text;\r\ntext-align: center;\r\ncolor: {5};\r\nfont-family: Arial, Helvetica, sans-serif;\r\nfont-size: 12px;\r\nfont-style: normal;\r\nfont-weight: 400;\r\nline-height: 35px;\r\n\">{6}%</span>\r\n            {7}\r\n        </div>\r\n    </div>\r\n</div>";


        //xuống
        public const string Reduced = "<img src=\"https://s3-sgn10.fptcloud.com/fsel/Images/MicrosoftTeamsimage_1706670763.png\" alt=\"\">";

        //lên
        public const string Increase = "<img src=\"https://s3-sgn10.fptcloud.com/fsel/Images/MicrosoftTeamsimage_1_1706670935.png\" alt=\"\">";

        //nhỏ hơn

        public const string Less = "<img src=\"https://s3-sgn10.fptcloud.com/fsel/Images/MicrosoftTeamsimage_2_1706671174.png\" alt=\"\">";

        //lớn hơn
        public const string Bigger = "<img src=\"https://s3-sgn10.fptcloud.com/fsel/Images/MicrosoftTeamsimage_3_1706671196.png\" alt=\"\">";
        //bằng
        public const string Equal = "<img src=\"https://s3-sgn10.fptcloud.com/fsel/Images/MicrosoftTeamsimage_4_1706671214.png\" alt=\"\">";

        public const string Display = "style=\"width:100%;display: none;\"";

        public const string CompareSkill1 = "<div style=\"width:100%\">\r\n    <div style=\"margin-bottom:26px;width:100%;text-align:center\">\r\n        <div style=\"width:100%\">\r\n            <div style=\"margin-bottom:26px;width:100%;text-align:center\">\r\n                \r\n\r\n                <div style=\"display:flex;margin-top:26px\">\r\n                    <div style=\"display:flex;width:100%\">\r\n\r\n                        <div style=\"width:10%\">\r\n                            <img src=\"{0}\" alt=\"\" class=\"CToWUd\" data-bit=\"iit\">\r\n                        </div>\r\n                        <div style=\"width: 45%;margin-right:5%\">\r\n                            <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:600;line-height:22px;margin-bottom:6px;width:100%\">\r\n                                {1}\r\n                            </div>\r\n                            <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:18px;font-style:normal;font-weight:600;line-height:20px;width:100%\">\r\n                                <div style=\"width:100%;display:flex\">\r\n                                    <div style=\"width:{2}%;display:flex;height:10px;border-radius:100px 0 0 100px;background:#53bf65\"></div>\r\n                                    <div style=\"display:flex;width:{3}%;height:10px;border-radius:0 100px 100px 0;background:#e2e4e9\"></div>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <div style=\"padding:14px 10px;border-radius:8px;border:1px solid #809fe5;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:400;line-height:24px;width: 45%;text-align:center\">\r\n                            <div style=\"margin:0 11px\">\r\n                                <span style=\"text-align:center;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size: 20px;font-style:normal;font-weight:400;line-height:35px\">\r\n                                    {4}%\r\n                                </span>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>";


        public const string CompareSkill2 = "<div style=\"display:flex;margin-top:26px\">\r\n    <div style=\"display:flex;width:100%\">\r\n\r\n        <div style=\"width:10%\">\r\n            <img src=\"{0}\" alt=\"\" class=\"CToWUd\" data-bit=\"iit\">\r\n        </div>\r\n        <div style=\"width:45%;margin-right:5%\">\r\n            <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:18px;font-style:normal;font-weight:600;line-height:20px;margin-bottom:6px;width:100%\">\r\n               {1}\r\n            </div>\r\n            <div style=\"display:flex;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:600;line-height:22px;width:100%\">\r\n                <div style=\"width:100%;display:flex\">\r\n                    <div style=\"width:{2}%;display:flex;height:10px;border-radius:100px 0 0 100px;background:#53bf65\"></div>\r\n                    <div style=\"display:flex;width:{3}%;height:10px;border-radius:0 100px 100px 0;background:#e2e4e9\"></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div style=\"display:flex;padding:14px 10px;border-radius:8px;border:1px solid #809fe5;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:400;line-height:24px;width: 45%;\">\r\n            <div style=\"margin:0 11px;width:45%;text-align:center\">\r\n                <span style=\"text-align:center;color:#3a4b78;font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:400;line-height:35px\">\r\n                    {4}%\r\n                </span>\r\n            </div>\r\n\r\n            <div style=\"width:1px;height:35px;background:#809fe5;margin:0 2px\"></div>\r\n\r\n            <span style=\"background:#cc666f;background-clip:text;text-align:center;color:{5};font-family:Arial,Helvetica,sans-serif;font-size:20px;font-style:normal;font-weight:400;line-height:35px;width:50%\">{6}%</span>\r\n            \r\n        </div>\r\n    </div>\r\n</div>";

        public const string LessonName = "<div style=\"\r\n                        margin-bottom: 26px;\r\n                        width: 100%;\r\n                        text-align: center;\r\n                      \">\r\n                                                    <div style=\"margin-bottom: 26px\">\r\n                                                        <span style=\"\r\n                            text-align: center;\r\n                            color: #3a4b78;\r\n                            font-family: Arial, Helvetica, sans-serif;\r\n                            font-size: 20px;\r\n                            font-style: normal;\r\n                            font-weight: 700;\r\n                            line-height: 24px;\r\n                          \">\r\n                                                            Bài học số\r\n                                                            <span style=\"\r\n                              text-align: center;\r\n                              color: #809fe5;\r\n                              font-family: Arial, Helvetica,\r\n                                sans-serif;\r\n                              font-size: 32px;\r\n                              font-style: normal;\r\n                              font-weight: 400;\r\n                              line-height: 40px;\r\n                            \">\r\n                                                                {0}\r\n                                                            </span>\r\n                                                        </span>\r\n                                                    </div>\r\n                                                    <div style=\"\r\n                          color: var(\r\n                            --FSEL_LMS-Sys-suface-container-lowest,\r\n                            #212b45\r\n                          );\r\n                          text-align: center;\r\n                          font-family: Arial, Helvetica,sans-serif;\r\n                          font-size: 20px;\r\n                          font-style: normal;\r\n                          font-weight: 400;\r\n                          line-height: 24px;\r\n                        \">\r\n                                                        {1} - {2}\r\n                                                    </div>\r\n                                                </div>";
        public const string UnitName = "<div style=\"\r\n                        margin-bottom: 26px;\r\n                        color: #809fe5;\r\n                        text-align: center;\r\n                        font-family: Arial, Helvetica, sans-serif;\r\n                        font-size: 32px;\r\n                        font-style: normal;\r\n                        font-weight: 400;\r\n                        line-height: 40px;\r\n                      \">\r\n                                                    <span>{0}</span>\r\n                                                </div>";

        public const string Active = "https://s3-sgn10.fptcloud.com/fsel/Images/Function.png";
        public const string NoActive = "https://s3-sgn10.fptcloud.com/fsel/Images/Ellipse_925_1706799389.png";
    }
}
