<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsUseCore>true</IsUseCore>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Fsel.Shared\Fsel.Shared.csproj" />
  </ItemGroup>

</Project>
