<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\CommandModels\ChatBot\**" />
    <EmbeddedResource Remove="Models\CommandModels\ChatBot\**" />
    <None Remove="Models\CommandModels\ChatBot\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Models\CommandModels\Classes\" />
    <Folder Include="Models\CommandModels\PlacementTestResults\" />
    <Folder Include="Models\QueryModels\NewFolder\" />
    <Folder Include="Models\QueryModels\VideoTimeCodeResults\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Fsel.Shared\Fsel.Shared.csproj" />
  </ItemGroup>

</Project>
