<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\SurveyQuestionCmd\" />
    <Folder Include="Services\OrderService\Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.Interaction.Infrastructure\Fsel.Interaction.Infrastructure.csproj" />
  </ItemGroup>

</Project>
