<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.Identity.Infrastructure\Fsel.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\GoogleSheetReadingCmd\" />
    <Folder Include="Services\GoogleSheetServices\Models\" />
  </ItemGroup>

</Project>
