<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Fsel.Sender\Fsel.Sender.Application\Fsel.Sender.Application.csproj" />
    <ProjectReference Include="..\Fsel.Identity.Infrastructure\Fsel.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
