<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\FFmpegServices\CommandModels\**" />
    <EmbeddedResource Remove="Services\FFmpegServices\CommandModels\**" />
    <None Remove="Services\FFmpegServices\CommandModels\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsel.Course.Infrastructure\Fsel.Course.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\LearningGoalCmd\" />
    <Folder Include="Services\SystemService\QueryModels\Schools\" />
  </ItemGroup>

</Project>
