version: '3.5'
services:
    sender.service:
        container_name: sender.service
        hostname: SenderService
        image: ${DOCKER_REGISTRY-}sender-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Sender.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - SERVICENAME=Sender
            - SentryConfig__Dsn=https://530c364a1c006e0dade385d197373f4a@o4505797571444736.ingest.sentry.io/4505797729452032
            - SMTP__FROM=fsel@atlantic.edu.vn
            - SMTP__SMTPSERVER=smtp.gmail.com
            - SMTP__PORT=465
            - SMTP__USERNAME=fsel@atlantic.edu.vn
            - SMTP__PASSWORD=klnghinrhonlvgbf
        ports:
            - 5206:80
            - 7206:443