version: '3.5'
services:
    ordering.service:
        container_name: ordering.service
        hostname: OrderingService
        image: ${DOCKER_REGISTRY-}ordering-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Ordering.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.ordering-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Ordering
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - SERVICES_UserApiUrl=http://202.134.19.161:5202/api/v1
        ports:
            - 5209:80
            - 7209:443