version: '3.5'
services:
    lcms.service:
        container_name: lcms.service
        hostname: LcmsService
        image: ${DOCKER_REGISTRY-}lcms-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Lcms.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.course-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Lcms Course
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - SERVICES_UserApiUrl=http://202.134.19.161:5202/api/v1
        ports:
            - 5203:80
            - 7203:443
    lms.service:
        container_name: lms.service
        hostname: LmsService
        image: ${DOCKER_REGISTRY-}lms-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Lms.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.course-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Lms Course
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - SERVICES_UserApiUrl=http://202.134.19.161:5202/api/v1
            - SERVICES_ClassApiUrl=http://202.134.19.161:5207/api/v1
        ports:
            - 5204:80
            - 7204:443