version: '3.5'
services:
    system.service:
        container_name: system.service
        hostname: SystemService
        image: ${DOCKER_REGISTRY-}system-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/System.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.system-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=System
            - SentryConfig__Dsn=https://3c246735e89d4aebfe43ad11ff86ca2e@o4506116054384640.ingest.sentry.io/4506116055302144
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - SERVICES_UserApiUrl=http://user-testing.fsel-testing.svc/api/v1
            - SERVICES_OrderApiUrl=http://ordering-testing.fsel-testing.svc/api/v1
            - SERVICES_LmsCourseApiUrl=http://lmsapi-testing.fsel-testing.svc/api/v1
        ports:
            - 52010:80
            - 7010:443
