version: '3.5'
services:
    interaction.service:
        container_name: interaction.service
        hostname: InteractionService
        image: ${DOCKER_REGISTRY-}interaction-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Interaction.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.interaction-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Interaction
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - QueueConfig__RootUri=rabbitmq://42.96.58.145
            - QueueConfig__Username=admin
            - QueueConfig__Password=Fsel@2023
            - SERVICES_UserApiUrl=http://42.96.58.145:5202/api/v1
            - SERVICES_TrainingApiUrl=http://42.96.58.145:5207/api/v1
            - SERVICES_LmsCourseApiUrl=http://42.96.58.145:5204/api/v1
        ports:
            - 5208:80
            - 7208:443