version: '3.5'
services:
    realtime.host:
        container_name: realtime.host
        hostname: HangfireHost
        image: ${DOCKER_REGISTRY-}realtime-host:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Realtime.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - SERVICENAME=Realtime
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - QueueConfig__RootUri=rabbitmq://localhost
            - QueueConfig__Username=guest
            - QueueConfig__Password=guest
        ports:
            - 5501:80
            - 7501:443