version: '3.5'
services:
    realtime.host:
        container_name: realtime.host
        hostname: HangfireHost
        image: ${DOCKER_REGISTRY-}realtime-host:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Realtime.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - SERVICENAME=Realtime
            - SentryConfig__Dsn=https://530c364a1c006e0dade385d197373f4a@o4505797571444736.ingest.sentry.io/4505797729452032
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - QueueConfig__RootUri=rabbitmq://42.96.58.145
            - QueueConfig__Username=admin
            - QueueConfig__Password=Fsel@2023
        ports:
            - 5501:80
            - 7501:443