version: '3.5'
services:
    auth.service:
        container_name: auth.service
        hostname: AuthService
        image: ${DOCKER_REGISTRY-}auths-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Auth.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.user-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Auth
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - Otp__StepTime=3
            - Otp__StepDayWithAdmin=7
            - ConstantUrl__ConfirmOtpUrl=https://lms-admin-dev.fsel.edu.vn/login/first-login?otp={0}
            - SERVICES_SenderApiUrl=http://202.134.19.161:5206/api/v1
            - SERVICES_InteractionApiUrl=http://202.134.19.161:5208/api/
            - SERVICES_ClassApiUrl=http://202.134.19.161:5207/api/v1
        ports:
            - 5201:80
            - 7201:443
    user.service:
        container_name: user.service
        hostname: UserService
        image: ${DOCKER_REGISTRY-}users-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/User.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.user-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=User
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - Otp__StepTime=3
            - Otp__StepDayWithAdmin=7
            - ConstantUrl__ConfirmOtpUrl=https://lms-admin-dev.fsel.edu.vn/login/first-login?otp={0}
            - SERVICES_SenderApiUrl=http://202.134.19.161:5206/api/v1
            - SERVICES_InteractionApiUrl=http://202.134.19.161:5208/api/
            - SERVICES_ClassApiUrl=http://202.134.19.161:5207/api/v1
        ports:
            - 5202:80
            - 7202:443
