version: '3.5'
services:
    auth.service:
        container_name: auth.service
        hostname: AuthService
        image: ${DOCKER_REGISTRY-}auths-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/Auth.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.user-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=Auth
            - SentryConfig__Dsn=https://530c364a1c006e0dade385d197373f4a@o4505797571444736.ingest.sentry.io/4505797729452032
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - Otp__StepTime=3
            - Otp__StepDayWithAdmin=7
            - ConstantUrl__ConfirmOtpUrl=http://42.96.58.145:4300/login/first-login?otp={0}
            - SERVICES_SenderApiUrl=http://sender-testing.fsel-testing.svc/api/v1
            - SERVICES_InteractionApiUrl=http://interaction-testing.fsel-testing.svc/api/
            - SERVICES_ClassApiUrl=http://training-testing.fsel-testing.svc/api/v1
            - SERVICES_OrderApiUrl=http://ordering-testing.fsel-testing.svc/api/v1
            - SERVICES_LmsCourseApiUrl=http://lmsapi-testing.fsel-testing.svc/api/v1
        ports:
            - 5201:80
            - 7201:443
    user.service:
        container_name: user.service
        hostname: UserService
        image: ${DOCKER_REGISTRY-}users-microservice:v1
        build:
            context: ./../../
            dockerfile: Environments/Testing/User.Testing.Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Testing
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=183.91.11.235;Initial Catalog=env-dev.user-service;User Id=sa;Password=FselTech@2023;TrustServerCertificate=true;
            - SERVICENAME=User
            - SentryConfig__Dsn=https://530c364a1c006e0dade385d197373f4a@o4505797571444736.ingest.sentry.io/4505797729452032
            - JWT__SECRETKEY=JsonWebApiTokenWithSwaggerAuthorizationAuthenticationAspNetCore
            - JWT__ISSUER=baseWebApiIssuer
            - JWT__AUDIENCE=baseWebApiAudience
            - JWT__SUBJECT=baseWebApiSubject
            - JWT__TOKENVALIDITYINMINUTES=1440
            - JWT__REFRESHTOKENVALIDITYINDAYS=7
            - Otp__StepTime=3
            - Otp__StepDayWithAdmin=7
            - ConstantUrl__ConfirmOtpUrl=http://42.96.58.145:4300/login/first-login?otp={0}
            - SERVICES_SenderApiUrl=http://sender-testing.fsel-testing.svc/api/v1
            - SERVICES_InteractionApiUrl=http://interaction-testing.fsel-testing.svc/api/
            - SERVICES_ClassApiUrl=http://training-testing.fsel-testing.svc/api/v1
            - SERVICES_OrderApiUrl=http://ordering-testing.fsel-testing.svc/api/v1
            - SERVICES_LmsCourseApiUrl=http://lmsapi-testing.fsel-testing.svc/api/v1
        ports:
            - 5202:80
            - 7202:443